import * as THREE from 'three';

// Adapted mechanisms: the library's eight-coil reactor charge/surge and low-opacity tapered projector.
export function createProjector(scene){
 const group=new THREE.Group();group.position.y=1.90;scene.add(group);const coils=[],ticks=[];
 const base=new THREE.MeshStandardMaterial({color:0x17373c,metalness:.8,roughness:.3});
 const plate=new THREE.Mesh(new THREE.CylinderGeometry(1.27,1.19,.065,80),base);group.add(plate);
 const coreMat=new THREE.MeshStandardMaterial({color:0xafdaca,emissive:0x74dcca,emissiveIntensity:.6,metalness:.65,roughness:.25});
 const core=new THREE.Mesh(new THREE.CylinderGeometry(.43,.4,.07,64),coreMat);core.position.y=.06;group.add(core);
 for(let i=0;i<8;i++){const a=i*Math.PI/4;const mat=new THREE.MeshBasicMaterial({color:0x9af3dc,transparent:true,opacity:.1});const coil=new THREE.Mesh(new THREE.TorusGeometry(.16,.022,8,32),mat);coil.rotation.x=Math.PI/2;coil.position.set(Math.cos(a)*.87,.07,Math.sin(a)*.87);group.add(coil);coils.push(coil);}
 for(let i=0;i<24;i++){const a=i*Math.PI/12;const mat=new THREE.MeshBasicMaterial({color:0xc7fff1,transparent:true,opacity:.15});const tick=new THREE.Mesh(new THREE.BoxGeometry(.035,.008,.13),mat);tick.position.set(Math.cos(a)*1.12,.041,Math.sin(a)*1.12);tick.rotation.y=-a+Math.PI/2;group.add(tick);ticks.push(tick);}
 const beamMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{power:{value:0},tint:{value:new THREE.Color(0x92f4dd)}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec2 vUv;uniform float power;uniform vec3 tint;void main(){float endFade=smoothstep(0.,.1,vUv.y)*(1.-smoothstep(.75,1.,vUv.y));float strands=.65+.35*pow(.5+.5*sin(vUv.x*150.),8.);gl_FragColor=vec4(tint,.014*power*endFade*strands);}'});
 const beam=new THREE.Mesh(new THREE.CylinderGeometry(1.8,.12,5.0,64,1,true),beamMat);beam.position.y=2.55;group.add(beam);
 const scanMat=new THREE.MeshBasicMaterial({color:0xd6fff0,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending});const scan=new THREE.Mesh(new THREE.TorusGeometry(1,.012,8,90),scanMat);scan.rotation.x=Math.PI/2;group.add(scan);
 const seed=new Float32Array(420*3);for(let i=0;i<420;i++){seed[i*3]=i/420;seed[i*3+1]=Math.sin(i*71.31)*.5+.5;seed[i*3+2]=Math.cos(i*31.29)*.5+.5;}const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(seed,3));
 const moteMat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{time:{value:0},power:{value:0},tint:{value:new THREE.Color(0xa9ffdf)}},vertexShader:'uniform float time,power;varying float alpha;void main(){float h=fract(position.x+time*.16);float a=position.y*6.283;float r=(.12+h*1.6)*(.3+position.z*.7);vec3 p=vec3(cos(a)*r,h*4.9,sin(a)*r);vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(28./-mv.z,1.,3.);alpha=power*sin(h*3.14159)*.6;}',fragmentShader:'uniform vec3 tint;varying float alpha;void main(){float a=1.-smoothstep(.1,.5,length(gl_PointCoord-.5));gl_FragColor=vec4(tint,alpha*a);}'});const motes=new THREE.Points(geometry,moteMat);motes.frustumCulled=false;group.add(motes);
 let previousActive=false,surge=0;const color=new THREE.Color();
 function update({dt,time,charge,active,opening=0,kind='field',cue=0}){if(active&&!previousActive)surge=1.4;previousActive=active;surge=Math.max(0,surge-dt);const strength=active?.65:charge;const pulse=surge/1.4;const f=Math.max(strength,pulse,cue);color.set(kind==='tva'?0xffd49a:0xa0f3df);coreMat.emissive.copy(color);coreMat.emissiveIntensity=.6+f*1.4;core.scale.setScalar(1+pulse*.08);coils.forEach((m,i)=>{m.material.color.copy(color);m.material.opacity=.08+Math.max(0,Math.min(1,charge*8-i))*.8+(active?.34:0);});ticks.forEach((m,i)=>{m.material.color.copy(color);m.material.opacity=.12+((i/24)<f?.7:0);});beamMat.uniforms.power.value=f;beamMat.uniforms.tint.value.copy(color);moteMat.uniforms.time.value=time;moteMat.uniforms.power.value=f;moteMat.uniforms.tint.value.copy(color);const top=kind==='guide'?6.3:5.0;scan.position.y=.04+opening*top;scan.scale.setScalar(.12+opening*1.7);scanMat.opacity=active&&opening<.995?.6*Math.sin(opening*Math.PI):0;scanMat.color.copy(color);}
 function dispose(){scene.remove(group);const gs=new Set(),ms=new Set();group.traverse(o=>{if(o.geometry)gs.add(o.geometry);if(o.material)ms.add(o.material);});gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());}
 return {update,dispose};
}
